name: winddatas
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandas>=1.5
  - numpy>=1.23
  - requests>=2.28
  - matplotlib>=3.5
  - scipy>=1.8
  - plotly>=5.10
  - python-docx>=0.8
  - geopy>=2.2
  - meteostat>=1.6
  - cdsapi>=0.5
  - pydeck>=0.8
  - papermill>=2.4
  - pip
  - seaborn
  - pip:
      - meteostat
      - python-docx
